language: php

php:
  - '7.4'

before_install:
  - composer self-update --2

install:
  - composer install --prefer-dist --no-suggest

script:
  - composer ci

cache:
  directories:
    - "$HOME/.composer/cache/files"
