name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: PHPUnit unit tests - PHP ${{ matrix.php }} ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: [ubuntu-latest]
        php: ['8.0']
        psr-log: ['^1.1', '^2.0', '^3.0']

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup php
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}

      - name: Download dependencies
        uses: php-actions/composer@v6
        with:
          php_version: ${{ matrix.php-versions }}
          args: --ignore-platform-reqs --quiet

      - name: Download psr/log ${{ matrix.psr-log }}
        uses: php-actions/composer@v6
        with:
          command: require
          args: psr/log ${{ matrix.psr-log }}

      - name: Run PHPUnit unit tests
        run: composer test
