name: Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  unit:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: php-actions/composer@v2
        with:
          args: --ignore-platform-reqs --quiet

      - name: Run PHPUnit unit tests
        run: composer test
